// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/ahume/github-deployment-resource"
	"github.com/google/go-github/github"
)

type FakeGitHub struct {
	ListDeploymentsStub        func() ([]*github.Deployment, error)
	listDeploymentsMutex       sync.RWMutex
	listDeploymentsArgsForCall []struct{}
	listDeploymentsReturns     struct {
		result1 []*github.Deployment
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitHub) ListDeployments() ([]*github.Deployment, error) {
	fake.listDeploymentsMutex.Lock()
	fake.listDeploymentsArgsForCall = append(fake.listDeploymentsArgsForCall, struct{}{})
	fake.recordInvocation("ListDeployments", []interface{}{})
	fake.listDeploymentsMutex.Unlock()
	if fake.ListDeploymentsStub != nil {
		return fake.ListDeploymentsStub()
	} else {
		return fake.listDeploymentsReturns.result1, fake.listDeploymentsReturns.result2
	}
}

func (fake *FakeGitHub) ListDeploymentsCallCount() int {
	fake.listDeploymentsMutex.RLock()
	defer fake.listDeploymentsMutex.RUnlock()
	return len(fake.listDeploymentsArgsForCall)
}

func (fake *FakeGitHub) ListDeploymentsReturns(result1 []*github.Deployment, result2 error) {
	fake.ListDeploymentsStub = nil
	fake.listDeploymentsReturns = struct {
		result1 []*github.Deployment
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHub) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listDeploymentsMutex.RLock()
	defer fake.listDeploymentsMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeGitHub) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resource.GitHub = new(FakeGitHub)
