#!/bin/bash
# vim: set ft=sh

set -eu

# export GOPATH=$PWD/gopath
# export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/ahume/github-deployment-resource

go install github.com/ahume/github-deployment-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

./scripts/build

cp -a assets Dockerfile $BUILD_DIR
